# Generated by Django 3.2.4 on 2021-06-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('progress', models.CharField(choices=[('DEPLOYED', 'Deployed'), ('UNDER DEVELOPMENT', 'Under Development'), ('UNDER RESEARCH', 'Under Research'), ('SCHOLARSHIP WORK', 'Scholarship Work'), ('NOT STARTED', 'Not Started')], default='NOT STARTED', max_length=40)),
                ('suggested_by', models.CharField(max_length=200)),
                ('impacted_areas', models.CharField(max_length=200)),
                ('suggested_po', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinkAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_class', models.CharField(max_length=200)),
                ('core_id', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('progress', models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('DISMISSED', 'Dismissed'), ('TOOL SUBMIT', 'Tool Submit'), ('DEPLOYED', 'Deployed'), ('ON HOLD', 'On Hold')], default='IN PROGRESS', max_length=40)),
                ('researcher', models.CharField(choices=[('Doctor Degree', 'Doctor Degree'), ('Master Degree', 'Master Degree'), ('Scientific Initiation', 'Scientific Initiation'), ('N/A', 'N A')], default='N/A', max_length=40)),
                ('research_type', models.CharField(max_length=200)),
                ('po', models.CharField(max_length=200)),
                ('impacted_project_test_area', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('org', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('idea_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.idea')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_id', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('team_org', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='MonographInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monograph_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('residence_class', models.CharField(max_length=200)),
                ('po', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('idea_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.idea')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.professor')),
                ('related_links', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.linkaddress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='related_links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.linkaddress'),
        ),
        migrations.CreateModel(
            name='DevToolsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('DISMISSED', 'Dismissed'), ('TOOL SUBMIT', 'Tool Submit'), ('DEPLOYED', 'Deployed'), ('ON HOLD', 'On Hold'), ('PLANNED', 'Planned'), ('EVALUATING', 'Evaluating'), ('STARTING', 'Starting')], default='PLANNED', max_length=40)),
                ('current_version', models.CharField(max_length=200)),
                ('dependencies', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('devs', models.CharField(max_length=200)),
                ('po', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('idea_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.idea')),
                ('monograph_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.monographinfo')),
                ('related_links', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.linkaddress')),
                ('research_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.researchinfo')),
            ],
        ),
    ]
