# Generated by Django 3.2.4 on 2021-06-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0002_auto_20210605_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devtoolsproject',
            options={'ordering': ['idea_key', 'monograph_key', 'research_key', 'tool_key', 'tool_name', 'status', 'start_date', 'due_date']},
        ),
        migrations.AlterModelOptions(
            name='monographinfo',
            options={'ordering': ['monograph_key', 'idea_key', 'title', 'residence_class']},
        ),
        migrations.RemoveField(
            model_name='devtoolsproject',
            name='devs',
        ),
        migrations.AddField(
            model_name='devtoolsproject',
            name='devs',
            field=models.ManyToManyField(related_name='dev_tools_projects_devs', to='ideas_app.Person'),
        ),
        migrations.RemoveField(
            model_name='devtoolsproject',
            name='po',
        ),
        migrations.AddField(
            model_name='devtoolsproject',
            name='po',
            field=models.ManyToManyField(related_name='dev_tools_projects_po', to='ideas_app.Person'),
        ),
        migrations.RemoveField(
            model_name='devtoolsproject',
            name='related_links',
        ),
        migrations.AddField(
            model_name='devtoolsproject',
            name='related_links',
            field=models.ManyToManyField(related_name='dev_tools_projects_link', to='ideas_app.LinkAddress'),
        ),
        migrations.RemoveField(
            model_name='idea',
            name='related_links',
        ),
        migrations.AddField(
            model_name='idea',
            name='related_links',
            field=models.ManyToManyField(related_name='ideas_link', to='ideas_app.LinkAddress'),
        ),
        migrations.RemoveField(
            model_name='idea',
            name='suggested_po',
        ),
        migrations.AddField(
            model_name='idea',
            name='suggested_po',
            field=models.ManyToManyField(related_name='ideas_po', to='ideas_app.Person'),
        ),
        migrations.RemoveField(
            model_name='monographinfo',
            name='po',
        ),
        migrations.AddField(
            model_name='monographinfo',
            name='po',
            field=models.ManyToManyField(related_name='monograph_infos_po', to='ideas_app.Person'),
        ),
        migrations.RemoveField(
            model_name='monographinfo',
            name='professor',
        ),
        migrations.AddField(
            model_name='monographinfo',
            name='professor',
            field=models.ManyToManyField(related_name='monograph_infos_professor', to='ideas_app.Professor'),
        ),
        migrations.RemoveField(
            model_name='monographinfo',
            name='related_links',
        ),
        migrations.AddField(
            model_name='monographinfo',
            name='related_links',
            field=models.ManyToManyField(related_name='monograph_infos_link', to='ideas_app.LinkAddress'),
        ),
        migrations.RemoveField(
            model_name='monographinfo',
            name='student',
        ),
        migrations.AddField(
            model_name='monographinfo',
            name='student',
            field=models.ManyToManyField(related_name='monograph_infos_residence_student', to='ideas_app.ResidenceStudent'),
        ),
        migrations.RemoveField(
            model_name='researchinfo',
            name='po',
        ),
        migrations.AddField(
            model_name='researchinfo',
            name='po',
            field=models.ManyToManyField(related_name='research_infos_po', to='ideas_app.Person'),
        ),
    ]
