# Generated by Django 3.2.4 on 2021-06-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0006_alter_institute_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchinfo',
            name='research_key',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='researchinfo',
            name='research_type',
            field=models.CharField(choices=[('Doctor Degree', 'Doctor Degree'), ('Master Degree', 'Master Degree'), ('Scientific Initiation', 'Scientific Initiation'), ('N/A', 'N A')], default='N/A', max_length=40),
        ),
        migrations.AlterField(
            model_name='researchinfo',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideas_app.researcher'),
        ),
    ]
